# Generated by Django 3.1.5 on 2024-04-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0025_auto_20240421_0618'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('billing_date', models.DateField()),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('billing_no', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('fee', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], max_length=2)),
                ('transfer_account', models.CharField(blank=True, max_length=255, null=True)),
                ('person_in_charge', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.IntegerField(default=0)),
                ('available', models.CharField(blank=True, default='T', max_length=1, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TraderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_same_order', models.IntegerField(default=0, null=True)),
                ('sale_same_order', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraderPurchasesSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Product'), ('D', 'Document')], max_length=1)),
                ('desired_arrival_date', models.DateField(blank=True, null=True)),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraderSalesSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Product'), ('D', 'Document')], max_length=1)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesender',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='salesender',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='contractdocumentfee',
            name='number_of_models',
        ),
        migrations.RemoveField(
            model_name='contractdocumentfee',
            name='number_of_units',
        ),
        migrations.RemoveField(
            model_name='contractproduct',
            name='type',
        ),
        migrations.RemoveField(
            model_name='hallpurchasescontract',
            name='insurance_fee',
        ),
        migrations.RemoveField(
            model_name='hallpurchasescontract',
            name='insurance_fee_include',
        ),
        migrations.RemoveField(
            model_name='hallsalescontract',
            name='insurance_fee',
        ),
        migrations.RemoveField(
            model_name='hallsalescontract',
            name='insurance_fee_include',
        ),
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='insurance_fee',
        ),
        migrations.RemoveField(
            model_name='traderpurchasescontract',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='tradersalescontract',
            name='insurance_fee',
        ),
        migrations.AddField(
            model_name='contractdocumentfee',
            name='model_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractdocumentfee',
            name='unit_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='report_date',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallpurchasescontract',
            name='purchase_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallsalescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='hallsalescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hallsalescontract',
            name='sale_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='frame_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='purchase_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traderpurchasescontract',
            name='removal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='available',
            field=models.CharField(blank=True, default='T', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradersalescontract',
            name='sale_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='confirmor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer'),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.hall'),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='payment_method',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallpurchasescontract',
            name='transfer_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='confirmor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer'),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.hall'),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='payment_method',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='transfer_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='account_holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('D', 'Delivery'), ('R', 'Receipt'), ('C', 'ID Change'), ('B', '* Blank')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='traderpurchasescontract',
            name='transfer_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='payment_method',
            field=models.CharField(choices=[('TR', 'Transfer'), ('CR', 'Credit')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseSender',
        ),
        migrations.DeleteModel(
            name='SaleSender',
        ),
        migrations.AddField(
            model_name='tradersalessender',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='contracts.tradersalescontract'),
        ),
        migrations.AddField(
            model_name='tradersalessender',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.sender'),
        ),
        migrations.AddField(
            model_name='traderpurchasessender',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='contracts.traderpurchasescontract'),
        ),
        migrations.AddField(
            model_name='traderpurchasessender',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.sender'),
        ),
        migrations.AddField(
            model_name='traderlink',
            name='purchase_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_contract_link', to='contracts.contractproduct'),
        ),
        migrations.AddField(
            model_name='traderlink',
            name='sale_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_contract_link', to='contracts.contractproduct'),
        ),
    ]
