# Generated by Django 3.1.5 on 2024-04-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20240428_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecontract',
            name='own_company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicecontract',
            name='own_company_invoice_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicecontract',
            name='own_company_mailaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicecontract',
            name='own_company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicecontract',
            name='own_company_postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicecontract',
            name='own_company_tel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
