# Generated by Django 3.1.5 on 2024-05-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_deliverycontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecontract',
            name='payment_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
