# Generated by Django 3.1.5 on 2024-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_auto_20210720_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='excel',
        ),
        migrations.AddField(
            model_name='customer',
            name='payee',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
