# Generated by Django 3.1.5 on 2024-03-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0018_auto_20240302_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fax',
            new_name='mailaddress',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='fax',
            new_name='mailaddress',
        ),
        migrations.RenameField(
            model_name='sender',
            old_name='fax',
            new_name='mailaddress',
        ),
    ]
