# Generated by Django 3.1.5 on 2024-03-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20240302_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='excel',
        ),
        migrations.AddField(
            model_name='sender',
            name='payee',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
