# Generated by Django 3.1.5 on 2024-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_auto_20240302_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maker',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'Pachinko'), ('S', 'Slot'), ('categoryA', 'categoryA'), ('categoryB', 'categoryB'), ('categoryC', 'categoryC'), ('categoryD', 'categoryD')], default='categoryA', max_length=9),
        ),
        migrations.AlterField(
            model_name='documentfee',
            name='type',
            field=models.CharField(choices=[('P', 'Pachinko'), ('S', 'Slot'), ('categoryA', 'categoryA'), ('categoryB', 'categoryB'), ('categoryC', 'categoryC'), ('categoryD', 'categoryD')], default='categoryA', max_length=9),
        ),
    ]
