# Generated by Django 3.1.5 on 2024-04-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0022_inventoryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='person_in_charge',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
