# Generated by Django 3.1.5 on 2024-04-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0023_auto_20240421_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
