# Generated by Django 3.1.5 on 2024-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0024_auto_20240421_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
